### ISSUE TITLE
Ray takes window focus after being triggered

### ISSUE THREAD

**Issue by danielpost** [spatie/ray#24]
**Describe the bug**
When refreshing the browser on a page that has a `ray` call, the window focus automatically switches to the Ray window rather than staying in the browser. I don't know if this is intentional (it very well might be) but it would be great to have the ability to turn this off and keep window focus in the browser. I usually just need to look at Ray (on 2nd monitor) and don't need it to be focused.

Also, thanks for this awesome little app!

**Versions**
1.0.1

**To Reproduce**
1. Add `ray('Test')` to PHP file.
2. Refresh browser.

**Desktop (please complete the following information):**
 - macOS 11

**Comment by miclf** [comment]
I have the same issue (on macOS too).

I use Ray with a maximized window, on a single screen. I use `cmd + tab` to switch between Ray and my browser / terminal / database GUI / whatever.

In addition to Ray automatically stealing focus for regular calls to `ray()`, this makes it impossible to switch to another app when using the `pause()` method, because Ray then takes the focus at the very millisecond I try to `cmd + tab` to another app. Thus preventing me to check the result of a query in a database table, for example.
I need to click one of the buttons to explicitly allow my code to continue or force it to stop in order to have Ray release window focus, which defeats the purpose of what `pause()` is there in the first place 🤷‍♂️

**Comment by freekmurze** [comment]
We could reproduce this and will be releasing a fix soon.

**Comment by AdrianMrn** [comment]
This was fixed in https://github.com/spatie/ray-app/commit/3dd44553d7638bc2e623560646c730bc4442342c

**Comment by WebKenth** [comment]
@AdrianMrn Has this fix been implemented? i am still experiencing this
