### ISSUE TITLE
Windows: Quiting Ray doesn't kill its processes

### ISSUE THREAD

**Issue by slaFFik** [spatie/ray#44]
**Describe the bug**
When using "Menu > Quit Ray" the Ray itself is closed, but its processes (5 so far) are still present and not killed. 
When you quit Ray and try to uninstall it (to reinstall) - the Uninstall Tool that I use for this purpose says me that Ray is running in the background and whether I want to kill all the processes.

**Versions**
Ray version (you can see this in "About Ray"): 1.0.3

PHP version: 7.4

**To Reproduce**
1. Instrall Ray on Windows 10
2. Quit Ray
3. Observe all the Ray processes in the Task Manager.

**Expected behavior**

When quiting all processes should be killed.

**Screenshots**

![image](https://user-images.githubusercontent.com/282234/104005027-32e51c80-51ad-11eb-94c2-303443c1d321.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 20H2

**Comment by freekmurze** [comment]
This has been fixed in Ray v1.0.4

Just relaunch Ray to pull in updates.

**Comment by Eldair** [comment]
This is still an issue w/ the latest version as well
![image](https://user-images.githubusercontent.com/470003/104715336-b7441c00-5726-11eb-972a-82ed1402d062.png)

**Comment by AdrianMrn** [comment]
@Eldair This should only happen when Ray is minimized. Using the x button doesn't close it; it'll stay active in the background, like many other apps. If you use `file > quit ray`, or right click the tray icon and click `quit`, all processes should be gone.

The multiple background processes are -as far as I can tell- normal on Windows. You'll notice the same thing happens for pretty much every other background process.

**Comment by Eldair** [comment]
@AdrianMrn Thanks for the info, you're right. Problem is that tray icon is not enabled by default and if X button doesn't close it completely then tray icon should always be visible w/o the option to disable it (or kill app with X button if tray icon is not enabled).

**Comment by AdrianMrn** [comment]
I think I agree with you. It does seem unclear on Windows & Linux when there is no trace of the app on the dock or the tray, but it is still running in the background. This is handled slightly better on Mac, where it always stays on the dock if it's still running in the background.

Maybe the only 2 options should be "display on tray & dock" (default) and "display only on tray".

@freekmurze any thoughts on this, or OK if I implement it as mentioned here?

**Comment by freekmurze** [comment]
> Maybe the only 2 options should be "display on tray & dock" (default) and "display only on tray".

👍

**Comment by AdrianMrn** [comment]
This will be included in 1.14.0
