### ISSUE TITLE
Cannot connect via SSH with password

### ISSUE THREAD

**Issue by bpeperkamp** [spatie/ray#520]
If i add a server in the ray app (on macOS) it will save a SSH password, but when connecting it will still try to use a certificate.

Ray version: 1.15.0

**To Reproduce**
1. Go to 'remote servers'
2. Click on 'add server' or 'edit server'
3. Use a password
4. Click on connect

**Expected behavior**
It should use a password login. If i create an empty file the problem is fixed :)

**Screenshots**
![Screenshot 2021-07-23 at 17 11 28](https://user-images.githubusercontent.com/79835509/126802743-3f996732-d5ab-48cc-924a-ca2d336a1e2c.png)

**Desktop (please complete the following information):**
 - macOS
 - Version 11.4

**Comment by AdrianMrn** [comment]
This was fixed in Ray 1.16.0 (released just now)! 😃

**Comment by lloricode** [comment]
HI, using only SSH and still not working

im using 1.16.0 version of the App

![Screenshot from 2021-07-26 07-25-19](https://user-images.githubusercontent.com/8251344/126916733-a77d4d96-df2a-48a8-9acb-3c607566197f.png)
